### ISSUE TITLE
TVMM reproduce

### ISSUE THREAD

**Issue by Eurekaer** [IMCCretrieval/ProST#3]
Hello, I read from your paper that you reproduced the TVMM code. Can you share the code in this regard? Thank you very much.

**Comment by IMCCretrieval** [comment]
Thank you for your attention. We are very sorry that the code for TVMM was lost due to changes in the workplace. You can try to use the SPG network structure(https://github.com/IMCCretrieval/ProST/blob/main/modules/modeling.py#L282), event sentence matching (https://github.com/IMCCretrieval/ProST/blob/main/modules/modeling.py#L350) and variance loss(https://github.com/facebookresearch/vicreg/blob/main/main_vicreg.py#L207)  to implement TVMM.
